### ISSUE TITLE
Link Down

### ISSUE THREAD

**Issue by mamaspace** [autoboosh/extendscript-toolkit-jsxbintojsx-plugin#1]
https://github.com/autoboosh/jsxbin-to-jsx-converter

Link is down..Can you please reup

**Comment by autoboosh** [comment]
Unfortunately I can't. It's been taken down by a DMCA request.

**Comment by mamaspace** [comment]
so sad to hear...really wanted to try out your script for educational purpose. uhhhh...i'm late in seeing this post.
